### ISSUE TITLE
Cannot find pretrain/spc_p10.pth 

### ISSUE THREAD

**Issue by SunHaoOne** [SysCV/spc2#2] opened 2021-04-20 08:55 UTC
Hello,
     I noticed that spc2 is not updated to docker, and I tried to move spc2 files to docker, but some of the files do not have permission, and the administrator in docker is carla. （This question has been solved by exec to the container with a root authority ）

**Comment by SunHaoOne** [comment] 2021-04-20 13:07
After `docker exec -it -u -0 + containerID + bash`, I can change the files. Howerver, pretrain/spc_p10.pth is needed for initialization. Where is this pth file? Thanks.

**Comment by noahcao** [comment] 2021-04-28 08:31
Hi, @SunHaoOne Thanks so much for proposing these issues.

1. I have uploaded the pretrained weights. You could find it through the link in readme.
2. I can't reproduce this error which seems related to some renaming of model modules. If that happens again, you could use the non-strict mode to load the pretrained model and try again.
3. Have fixed the import path error.
4. Please remove the existing save path or set a new save path and try again. To avoid overwriting previous checkpoint, the script is not allowed to be executed if there has existed the same-named save path already.

I'm closing this issue. Please feel free to reopen it and follow up if you have further same issues.

**Closed by noahcao** 2021-04-28 08:31 UTC

**Comment by SunHaoOne** [comment] 2021-05-10 03:02
> Hi, @SunHaoOne Thanks so much for proposing these issues.
> 
> 1. I have uploaded the pretrained weights. You could find it through the link in readme.
> 2. I can't reproduce this error which seems related to some renaming of model modules. If that happens again, you could use the non-strict mode to load the pretrained model and try again.
> 3. Have fixed the import path error.
> 4. Please remove the existing save path or set a new save path and try again. To avoid overwriting previous checkpoint, the script is not allowed to be executed if there has existed the same-named save path already.
> 
> I'm closing this issue. Please feel free to reopen it and follow up if you have further same issues.

Sorry I haven’t got back to you sooner. Thanks again for your updated information, I am glad that it really solves some problemI tried your method and have fixed some issues👍. Now I have loaded the pretrain weights successfully.
Howerver , there still existed some issues as follows:
 ** How to set the args parameters for the first training?**
```

(spc) root@ab8df04932c5:~/spc3/scripts# sh train_carla.sh
No model to resume!
turn to the base pretrain model: pretrain/model_only_fpn50.pth
Starting new episode ...
Start training ...
args.sample_with_collision True
args.use_collision True
use_coll True
use colls_with False
cost tensor([0.0439, 0.0438, 0.0439, 0.0438, 0.0439, 0.0440, 0.0440, 0.0439, 0.0440,
        0.0438, 0.0439, 0.0439, 0.0439, 0.0439, 0.0439, 0.0439, 0.0439, 0.0439,
        0.0439, 0.0438], device='cuda:0')
cost tensor([0.0439, 0.0438, 0.0439, 0.0438, 0.0439, 0.0440, 0.0440, 0.0439, 0.0440,
        0.0438, 0.0439, 0.0439, 0.0439, 0.0439, 0.0439, 0.0439, 0.0439, 0.0439,
        0.0439, 0.0438], device='cuda:0')
cost tensor([0.0878, 0.0877, 0.0879, 0.0877, 0.0877, 0.0879, 0.0879, 0.0878, 0.0879,
        0.0877, 0.0877, 0.0878, 0.0878, 0.0879, 0.0877, 0.0879, 0.0878, 0.0878,
        0.0877, 0.0877], device='cuda:0')
cost tensor([0.1317, 0.1315, 0.1318, 0.1315, 0.1316, 0.1319, 0.1319, 0.1318, 0.1319,
        0.1315, 0.1316, 0.1317, 0.1317, 0.1318, 0.1316, 0.1318, 0.1317, 0.1317,
        0.1316, 0.1315], device='cuda:0')
use_ins_coll False
SAS True
Traceback (most recent call last):
  File "main.py", line 95, in <module>
    main()
  File "main.py", line 91, in main
    train_policy(args, env)
  File "/home/carla/spc3/train.py", line 335, in train_policy
    trainer.run()
  File "/home/carla/spc3/train.py", line 310, in run
    action, guide_action = self.amanager.sample_action(net=self.model, obs=obs, obs_var=obs_var,action_var=action_var, exploration=self.exploration, step=step, explore=num_episode % 2)
  File "/home/carla/spc3/actionsampler.py", line 160, in sample_action
    action = self._sample_action(p, net, obs_var, self.guides, action_var=action_var, testing=testing)
  File "/home/carla/spc3/actionsampler.py", line 134, in _sample_action
    cost, ins_cost = self.estimate_cost(net, imgs, this_action, action_var, None, None).data.cpu().numpy()
AttributeError: 'tuple' object has no attribute 'data'

```
It seems that ’cost‘ and 'ins_cost' are a tuple object, then I checked and found cost is a tensor but ins_cost is always int and equals to zero. Then the folling shows ‘use_ins_coll’ is False, and finally I found this error is caused by missing the args ‘use-colls-with', although I set this args in train_carla.sh, It faled to find this args.
```
       if use_ins_coll and self.args.SAS:
            ins_cos = self.add_cost(output, 'colls_with_prob', speeds, weight, with_cur=True)
            print("ins_cos=",ins_cos)
        else:
            ins_cos = 0
```

**Comment by atusi-nakajima** [comment] 2021-06-22 05:44
Thanks for your post.
Did you put the weights you downloaded in the readme in spc2/pretrain/ with their original names? Or did you rename the file to model_only_fpn50.pth?

**Comment by SunHaoOne** [comment] 2021-06-22 05:59
> Thanks for your post.
> Did you put the weights you downloaded in the readme in spc2/pretrain/ with their original names? Or did you rename the file to model_only_fpn50.pth?

Yes, I have put it in the file and renamed it, finally the pretrained model can be successfully loaded.

**Comment by noahcao** [comment] 2021-07-08 02:52
Update: I updated the provided pretrained weights again to solve some key naming imcompability issue. Have a try a let me know if there is any further issues.
